/**
 * Copyright 2012-2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * <p>Modifications copyright (C) 2017 Uber Technologies, Inc.
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file
 * except in compliance with the License. A copy of the License is located at
 *
 * <p>http://aws.amazon.com/apache2.0
 *
 * <p>or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.uber.cadence.entities;

import java.util.*;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * DO NOT EDIT THIS FILE.
 *
 * <p>This file is generated by cadence-idl custom generator for simple java entity
 *
 * <p>If you want to change the code, please modify the generator.
 * https://github.com/cadence-workflow/cadence-idl/tree/main/java/thrift/generator
 */
@Data
@Accessors(chain = true)
public class HistoryEvent {
  private long eventId;
  private long timestamp;
  private EventType eventType;
  private long version;
  private long taskId;
  private WorkflowExecutionStartedEventAttributes workflowExecutionStartedEventAttributes;
  private WorkflowExecutionCompletedEventAttributes workflowExecutionCompletedEventAttributes;
  private WorkflowExecutionFailedEventAttributes workflowExecutionFailedEventAttributes;
  private WorkflowExecutionTimedOutEventAttributes workflowExecutionTimedOutEventAttributes;
  private DecisionTaskScheduledEventAttributes decisionTaskScheduledEventAttributes;
  private DecisionTaskStartedEventAttributes decisionTaskStartedEventAttributes;
  private DecisionTaskCompletedEventAttributes decisionTaskCompletedEventAttributes;
  private DecisionTaskTimedOutEventAttributes decisionTaskTimedOutEventAttributes;
  private DecisionTaskFailedEventAttributes decisionTaskFailedEventAttributes;
  private ActivityTaskScheduledEventAttributes activityTaskScheduledEventAttributes;
  private ActivityTaskStartedEventAttributes activityTaskStartedEventAttributes;
  private ActivityTaskCompletedEventAttributes activityTaskCompletedEventAttributes;
  private ActivityTaskFailedEventAttributes activityTaskFailedEventAttributes;
  private ActivityTaskTimedOutEventAttributes activityTaskTimedOutEventAttributes;
  private TimerStartedEventAttributes timerStartedEventAttributes;
  private TimerFiredEventAttributes timerFiredEventAttributes;
  private ActivityTaskCancelRequestedEventAttributes activityTaskCancelRequestedEventAttributes;
  private RequestCancelActivityTaskFailedEventAttributes
      requestCancelActivityTaskFailedEventAttributes;
  private ActivityTaskCanceledEventAttributes activityTaskCanceledEventAttributes;
  private TimerCanceledEventAttributes timerCanceledEventAttributes;
  private CancelTimerFailedEventAttributes cancelTimerFailedEventAttributes;
  private MarkerRecordedEventAttributes markerRecordedEventAttributes;
  private WorkflowExecutionSignaledEventAttributes workflowExecutionSignaledEventAttributes;
  private WorkflowExecutionTerminatedEventAttributes workflowExecutionTerminatedEventAttributes;
  private WorkflowExecutionCancelRequestedEventAttributes
      workflowExecutionCancelRequestedEventAttributes;
  private WorkflowExecutionCanceledEventAttributes workflowExecutionCanceledEventAttributes;
  private RequestCancelExternalWorkflowExecutionInitiatedEventAttributes
      requestCancelExternalWorkflowExecutionInitiatedEventAttributes;
  private RequestCancelExternalWorkflowExecutionFailedEventAttributes
      requestCancelExternalWorkflowExecutionFailedEventAttributes;
  private ExternalWorkflowExecutionCancelRequestedEventAttributes
      externalWorkflowExecutionCancelRequestedEventAttributes;
  private WorkflowExecutionContinuedAsNewEventAttributes
      workflowExecutionContinuedAsNewEventAttributes;
  private StartChildWorkflowExecutionInitiatedEventAttributes
      startChildWorkflowExecutionInitiatedEventAttributes;
  private StartChildWorkflowExecutionFailedEventAttributes
      startChildWorkflowExecutionFailedEventAttributes;
  private ChildWorkflowExecutionStartedEventAttributes childWorkflowExecutionStartedEventAttributes;
  private ChildWorkflowExecutionCompletedEventAttributes
      childWorkflowExecutionCompletedEventAttributes;
  private ChildWorkflowExecutionFailedEventAttributes childWorkflowExecutionFailedEventAttributes;
  private ChildWorkflowExecutionCanceledEventAttributes
      childWorkflowExecutionCanceledEventAttributes;
  private ChildWorkflowExecutionTimedOutEventAttributes
      childWorkflowExecutionTimedOutEventAttributes;
  private ChildWorkflowExecutionTerminatedEventAttributes
      childWorkflowExecutionTerminatedEventAttributes;
  private SignalExternalWorkflowExecutionInitiatedEventAttributes
      signalExternalWorkflowExecutionInitiatedEventAttributes;
  private SignalExternalWorkflowExecutionFailedEventAttributes
      signalExternalWorkflowExecutionFailedEventAttributes;
  private ExternalWorkflowExecutionSignaledEventAttributes
      externalWorkflowExecutionSignaledEventAttributes;
  private UpsertWorkflowSearchAttributesEventAttributes
      upsertWorkflowSearchAttributesEventAttributes;
}
