/**
 * Copyright 2012-2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * <p>Modifications copyright (C) 2017 Uber Technologies, Inc.
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file
 * except in compliance with the License. A copy of the License is located at
 *
 * <p>http://aws.amazon.com/apache2.0
 *
 * <p>or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.uber.cadence.entities;

import java.util.*;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * DO NOT EDIT THIS FILE.
 *
 * <p>This file is generated by cadence-idl custom generator for simple java entity
 *
 * <p>If you want to change the code, please modify the generator.
 * https://github.com/cadence-workflow/cadence-idl/tree/main/java/thrift/generator
 */
@Data
@Accessors(chain = true)
public class WorkflowExecutionInfo {
  private WorkflowExecution execution;
  private WorkflowType type;
  private long startTime;
  private long closeTime;
  private WorkflowExecutionCloseStatus closeStatus;
  private long historyLength;
  private String parentDomainId;
  private String parentDomainName;
  private long parentInitatedId;
  private WorkflowExecution parentExecution;
  private long executionTime;
  private Memo memo;
  private SearchAttributes searchAttributes;
  private ResetPoints autoResetPoints;
  private String taskList;
  private boolean isCron;
  private long updateTime;
  private Map<String, String> partitionConfig;
}
