package com.uber.cadence.entities;

public enum CancelExternalWorkflowExecutionFailedCause {
    UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION,
    WORKFLOW_ALREADY_COMPLETED,
    WORKFLOW_ALREADY_CANCELED,
    WORKFLOW_ALREADY_TERMINATED,
    WORKFLOW_ALREADY_TIMED_OUT,
    WORKFLOW_ALREADY_FAILED,
    WORKFLOW_ALREADY_CONTINUED_AS_NEW
}
