package com.uber.cadence.entities;

public enum ChildWorkflowExecutionFailedCause {
    WORKFLOW_TYPE_DOES_NOT_EXIST,
    WORKFLOW_ALREADY_RUNNING,
    WORKFLOW_ALREADY_COMPLETED,
    WORKFLOW_ALREADY_CANCELED,
    WORKFLOW_ALREADY_TERMINATED,
    WORKFLOW_ALREADY_TIMED_OUT,
    WORKFLOW_ALREADY_FAILED,
    WORKFLOW_ALREADY_CONTINUED_AS_NEW,
    WORKFLOW_ALREADY_STARTED
}
