package com.uber.cadence.entities;


import lombok.Data;

@Data
public class Decision {
    private DecisionType decisionType;
    private ScheduleActivityTaskDecisionAttributes scheduleActivityTaskDecisionAttributes;
    private RequestCancelActivityTaskDecisionAttributes requestCancelActivityTaskDecisionAttributes;
    private StartTimerDecisionAttributes startTimerDecisionAttributes;
    private CompleteWorkflowExecutionDecisionAttributes completeWorkflowExecutionDecisionAttributes;
    private FailWorkflowExecutionDecisionAttributes failWorkflowExecutionDecisionAttributes;
    private CancelTimerDecisionAttributes cancelTimerDecisionAttributes;
    private CancelWorkflowExecutionDecisionAttributes cancelWorkflowExecutionDecisionAttributes;
    private RequestCancelExternalWorkflowExecutionDecisionAttributes requestCancelExternalWorkflowExecutionDecisionAttributes;
    private RecordMarkerDecisionAttributes recordMarkerDecisionAttributes;
    private ContinueAsNewWorkflowExecutionDecisionAttributes continueAsNewWorkflowExecutionDecisionAttributes;
    private StartChildWorkflowExecutionDecisionAttributes startChildWorkflowExecutionDecisionAttributes;
    private SignalExternalWorkflowExecutionDecisionAttributes signalExternalWorkflowExecutionDecisionAttributes;
    private UpsertWorkflowSearchAttributesDecisionAttributes upsertWorkflowSearchAttributesDecisionAttributes;
}
