package com.uber.cadence.entities;

public enum DecisionTaskFailedCause {
    UNHANDLED_DECISION,
    BAD_SCHEDULE_ACTIVITY_ATTRIBUTES,
    BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES,
    BAD_START_TIMER_ATTRIBUTES,
    BAD_CANCEL_TIMER_ATTRIBUTES,
    BAD_RECORD_MARKER_ATTRIBUTES,
    BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES,
    BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES,
    BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES,
    BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES,
    BAD_CONTINUE_AS_NEW_ATTRIBUTES,
    START_TIMER_DUPLICATE_ID,
    RESET_STICKY_TASKLIST,
    WORKFLOW_WORKER_UNHANDLED_FAILURE,
    BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES,
    BAD_START_CHILD_EXECUTION_ATTRIBUTES,
    FORCE_CLOSE_DECISION,
    FAILOVER_CLOSE_DECISION,
    BAD_SIGNAL_INPUT_SIZE,
    RESET_WORKFLOW,
    BAD_BINARY,
    SCHEDULE_ACTIVITY_DUPLICATE_ID,
    BAD_SEARCH_ATTRIBUTES;
}
